[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[studio]
  enabled = true
  path = "/admin"
  allowed_roles = ["admin"]
  allowed_emails = ["saurabh.alhat@gmail.com"] 