[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)content'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[studio]
  enabled = true
  path = "/admin"
  allowed_roles = ["admin"]
  allowed_emails = ["saurabh.alhat@gmail.com"]

[visual]
  enable = true
  host = "saurabhalhatportfolio.netlify.app"
  disable_identity = false
  base_url = "/"

[context.preview]
  command = "npm run build:dev"

[context.preview.environment]
  NODE_ENV = "development"

[dev]
  framework = "vite"
  targetPort = 8080
  port = 3000
  command = "npm run dev" 