backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "case-studies"
    label: "Case Studies"
    folder: "src/posts/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "GitHub Link", name: "github", widget: "string", required: false }
      - { label: "Live Demo Link", name: "liveDemo", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false } # Add draft field
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog Posts"
    folder: "src/posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Read Time", name: "readTime", widget: "string" }
      - { label: "Image URL", name: "imageUrl", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Display on Homepage", name: "displayOnHomepage", widget: "boolean", default: true, required: false } # Add field to control homepage display
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false } # Add draft field
      - { label: "Content", name: "body", widget: "markdown" }