// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vklhopqcgxuadeiufidg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbGhvcHFjZ3h1YWRlaXVmaWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDU1NjMsImV4cCI6MjA2MDI4MTU2M30.PRijlYCh4E8npEk0xJ7kGuVbYAh_LgXQCvqvXKFYfGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);